import { promises as fs } from "node:fs";
import path from "node:path";
import { generateEmblemSvg } from "../server/identity/IdentityEmblems";
import {
  defaultEmblemDir,
  defaultIdentityRegistryDir,
  loadAgentRegistry,
} from "../server/identity/IdentityRegistry";

/**
 * `npm run identity:generate-emblems` — (re)writes every registered Agent's
 * deterministic SVG emblem to `resources/identity/emblems/<agentId>.svg`.
 * Idempotent: an agent whose generated bytes already match the file on disk
 * is reported unchanged, never rewritten (keeps `git diff` limited to
 * agents that actually need a new emblem — a new registration, or the
 * generator itself changing).
 */
async function main(): Promise<void> {
  const dir = process.argv.includes("--dir")
    ? process.argv[process.argv.indexOf("--dir") + 1]
    : defaultIdentityRegistryDir;
  const agents = await loadAgentRegistry(
    path.join(dir, "agents.json"),
  );
  const emblemDir = defaultEmblemDir(dir);
  await fs.mkdir(emblemDir, { recursive: true });

  let written = 0;
  let unchanged = 0;
  for (const agent of agents) {
    const svg = generateEmblemSvg(agent.id);
    const filePath = path.join(emblemDir, `${agent.id}.svg`);
    const existing = await fs.readFile(filePath, "utf8").catch(() => null);
    if (existing === svg) {
      unchanged++;
      continue;
    }
    await fs.writeFile(filePath, svg, "utf8");
    written++;
    console.log(`wrote ${path.relative(process.cwd(), filePath)}`);
  }
  console.log(
    `identity:generate-emblems — ${written} written, ${unchanged} already up to date, ${agents.length} agents total`,
  );
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
