import { randomBytes } from "node:crypto";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { z } from "zod";
import { resolveFeaturedMatchStateRoot } from "../FeaturedMatch";
import { withFileMutex } from "../FileMutex";

/**
 * Season Zero activation prompt Phase 4 ("Event package") — the typed,
 * OPERATOR-AUTHORED completeness record layered on top of one
 * `FeaturedMatch` (spec §2's public event package field list: title,
 * subtitle, evidence-backed reason to watch, participant identity,
 * versions, map/format, schedule, canonical URLs,
 * embargo state). Generated by `premiere:package` (interactive-free —
 * see that script's own doc) from real evidence, then operator-editable
 * prose fields on top.
 *
 * Deliberately a SEPARATE store from `FeaturedMatch.ts`, not a field
 * folded onto that schema: `FeaturedMatch` is the operational record
 * (created the instant a candidate is scheduled, mutated by the premiere
 * runtime's own reconcile pass); an `EventPackage` is editorial content an
 * operator iterates on over several sessions before it is "complete
 * enough" to pass `EventPackageGate.ts`'s `isPubliclyPromotable` check.
 * Participant identity/exact-version resolution is NEVER duplicated here —
 * `EventPackageGate.ts` reads it straight off the `FeaturedMatch` record's
 * own `participants[]` (see that module's doc) — this type only carries
 * the fields that exist NOWHERE else.
 *
 * Storage: a locked, atomically-written JSON store, same read/write/mutate
 * shape as `FeaturedMatch.ts` (copied rather than shared — see that
 * module's own doc for why: three lines, not worth a shared util). Locking
 * matters here because a future authenticated operator surface (spec:
 * "small authenticated operator surface") could edit the same package
 * concurrently with a CLI regeneration; unlike the Season registry (see
 * `SeasonRegistry.ts`'s doc) this is not git-reviewed tracked content.
 */

export const EventPackageClaimSourceSchema = z.enum([
  "standings_rank",
  "version_debut",
  "head_to_head",
  "recent_form",
]);
export type EventPackageClaimSource = z.infer<
  typeof EventPackageClaimSourceSchema
>;

/**
 * One evidence-backed clause of a reason-to-watch (spec: "The candidate
 * system should emit evidence, not merely a score" / "Auri v43 debuts
 * after v42 won four of its last five retained matches"). `reference`
 * MUST name the concrete data the claim rests on (an agent/version id, a
 * standings rank, a set of episode ids) — never blank. See
 * `CandidateReasonToWatch.ts` for the builder that produces these from
 * real registry/mirror data, and `EventPackageProseClaims.ts` for the
 * separate, conservative check that free-text prose fields don't smuggle
 * in an unreferenced factual claim of their own.
 */
export const EventPackageClaimSchema = z
  .object({
    text: z.string().min(1),
    source: EventPackageClaimSourceSchema,
    reference: z.string().min(1),
  })
  .strict();
export type EventPackageClaim = z.infer<typeof EventPackageClaimSchema>;

export const EventPackageReasonToWatchSchema = z
  .object({
    claims: z.array(EventPackageClaimSchema),
  })
  .strict();
export type EventPackageReasonToWatch = z.infer<
  typeof EventPackageReasonToWatchSchema
>;

/**
 * Whether the RESULT this package's match will produce (or produced) is
 * still under embargo. Distinct from `FeaturedMatch.state`/`result` (the
 * actual embargo enforcement — see that module's own doc): this is the
 * package's own "embargo checklist" field (spec: "embargo checklist"),
 * cross-checked for CONSISTENCY against the underlying match by
 * `EventPackageGate.ts`, never trusted alone.
 */
export const EventPackageEmbargoStateSchema = z.enum(["embargoed", "revealed"]);
export type EventPackageEmbargoState = z.infer<
  typeof EventPackageEmbargoStateSchema
>;

export const EventPackageSchema = z
  .object({
    schemaVersion: z.literal(1),
    featuredMatchId: z
      .string()
      .regex(/^feat_[a-f0-9]{20}$/, "expected feat_<20 lowercase hex>"),
    title: z.string().min(1),
    subtitle: z.string().min(1),
    reasonToWatch: EventPackageReasonToWatchSchema,
    mapLabel: z.string().min(1),
    format: z.string().min(1),
    /** The package's own copy of the scheduled time — kept in sync with `FeaturedMatch.scheduledAt` by `premiere:package` on regeneration; `EventPackageGate.ts` requires the two to agree for a premiere-lane match. */
    scheduledAt: z.string().nullable(),
    canonicalMatchUrl: z.string().min(1),
    /** Null for an archive-lane package (already-public league match — no premiere ever runs for it) and required for a premiere-lane one — see `EventPackageGate.ts`. */
    canonicalPremiereUrl: z.string().min(1).nullable(),
    embargoState: EventPackageEmbargoStateSchema,
    /** Operator-editable free prose — version-change notes, extra color beyond the structured claims above. Never blocks a save; `EventPackageProseClaims.ts`'s `findUnreferencedProseClaims` only WARNS an operator about an unbacked factual mention here. */
    editorialNotes: z.string(),
    createdAt: z.string(),
    updatedAt: z.string(),
    /** Retired with Director Cut's removal. Accepted (never required) ONLY so a pre-removal `event-packages.json` record still parses; stripped by the `.transform()` below so `EventPackage` itself never carries it again — a genuinely unknown key still fails `.strict()`. */
    directorCutEstimateSeconds: z
      .number()
      .int()
      .positive()
      .nullable()
      .optional(),
  })
  .strict()
  .transform(
    ({ directorCutEstimateSeconds: _legacy, ...eventPackage }) => eventPackage,
  );
export type EventPackage = z.infer<typeof EventPackageSchema>;

const EventPackageStoreFileSchema = z
  .object({
    schemaVersion: z.literal(1),
    packages: z.array(EventPackageSchema),
  })
  .strict();
export type EventPackageStoreFile = z.infer<typeof EventPackageStoreFileSchema>;

export const EMPTY_EVENT_PACKAGE_STORE: EventPackageStoreFile = {
  schemaVersion: 1,
  packages: [],
};

const STORE_FILE_NAME = "event-packages.json";
export const EVENT_PACKAGE_STATE_ROOT_ENV =
  "PROXYWAR_EVENT_PACKAGE_STATE_ROOT" as const;

/**
 * Same physical state directory `FeaturedMatch.ts` already resolves by
 * default — an `EventPackage` is 1:1 satellite data for one
 * `FeaturedMatch` id, not a separate operational domain, so there is no
 * reason to require a second env var in every deploy env file. Still
 * independently overridable (its own env var) for test isolation.
 */
export function resolveEventPackageStateRoot(
  environment: Record<string, string | undefined> = process.env,
  homeDirectory: string = os.homedir(),
): string {
  const configured = environment[EVENT_PACKAGE_STATE_ROOT_ENV]?.trim();
  if (configured !== undefined && configured !== "") {
    return path.resolve(configured);
  }
  return resolveFeaturedMatchStateRoot(environment, homeDirectory);
}

function errorCode(error: unknown): string | undefined {
  return error !== null && typeof error === "object" && "code" in error
    ? String((error as { code: unknown }).code)
    : undefined;
}

async function writeFileAtomic(
  destinationPath: string,
  contents: string,
): Promise<void> {
  const temporaryPath = `${destinationPath}.${process.pid}.${randomBytes(6).toString("hex")}.tmp`;
  try {
    await fs.writeFile(temporaryPath, contents);
    await fs.rename(temporaryPath, destinationPath);
  } catch (error) {
    await fs.rm(temporaryPath, { force: true }).catch(() => undefined);
    throw error;
  }
}

/** Same "empty on cold start, throw on corruption" contract as `readFeaturedMatchStore`. */
export async function readEventPackageStore(
  stateRoot: string,
): Promise<EventPackageStoreFile> {
  const filePath = path.join(stateRoot, STORE_FILE_NAME);
  let raw: string;
  try {
    raw = await fs.readFile(filePath, "utf8");
  } catch (error) {
    if (errorCode(error) === "ENOENT") {
      return EMPTY_EVENT_PACKAGE_STORE;
    }
    throw error;
  }
  return EventPackageStoreFileSchema.parse(JSON.parse(raw));
}

export async function writeEventPackageStoreUnlocked(
  stateRoot: string,
  file: EventPackageStoreFile,
): Promise<void> {
  const validated = EventPackageStoreFileSchema.parse(file);
  await fs.mkdir(stateRoot, { recursive: true });
  await writeFileAtomic(
    path.join(stateRoot, STORE_FILE_NAME),
    `${JSON.stringify(validated, null, 2)}\n`,
  );
}

export async function writeEventPackageStore(
  stateRoot: string,
  file: EventPackageStoreFile,
): Promise<void> {
  await withFileMutex(stateRoot, () =>
    writeEventPackageStoreUnlocked(stateRoot, file),
  );
}

/** Canonical read-modify-write primitive — same contract as `mutateFeaturedMatchStore`: one cross-process lock across the whole read -> mutate -> write cycle. */
export async function mutateEventPackageStore(
  stateRoot: string,
  mutate: (file: EventPackageStoreFile) => EventPackageStoreFile,
): Promise<EventPackageStoreFile> {
  return withFileMutex(stateRoot, async () => {
    const current = await readEventPackageStore(stateRoot);
    const next = mutate(current);
    await writeEventPackageStoreUnlocked(stateRoot, next);
    return next;
  });
}

/** Upserts one package by `featuredMatchId` (at most one package per match — never duplicated). */
export async function upsertEventPackage(
  stateRoot: string,
  pkg: EventPackage,
): Promise<EventPackageStoreFile> {
  const validated = EventPackageSchema.parse(pkg);
  return mutateEventPackageStore(stateRoot, (current) => ({
    ...current,
    packages: [
      ...current.packages.filter(
        (entry) => entry.featuredMatchId !== validated.featuredMatchId,
      ),
      validated,
    ],
  }));
}

/** Read-only lookup — `null` when no package has been generated for this match yet (the honest, expected pre-`premiere:package` state — see `EventPackageGate.ts`, which treats this as "not publicly promotable", never a crash). */
export function findEventPackage(
  store: EventPackageStoreFile,
  featuredMatchId: string,
): EventPackage | null {
  return (
    store.packages.find((entry) => entry.featuredMatchId === featuredMatchId) ??
    null
  );
}
